export interface Automation {
  id: string;
  name: string;
  description: string;
  apps: string[];
  status: "active" | "idle" | "error";
  type: "general" | "project" | "one-off";
  steps: string[];
  runCount: number;
  project?: string[]; // project ids from projects.ts
}

export const initialAutomations: Automation[] = [
  // Q3 Brand campaign (proj_1) - 3 automations
  {
    id: "1",
    name: "Research Synthesis",
    description: "Synthesize research findings from multiple sources",
    apps: ["Dovetail", "Google Docs"],
    status: "idle",
    type: "project",
    steps: [
      "gathering sources from dovetail",
      "analyzing data",
      "synthesizing findings",
      "generating report in google docs",
    ],
    runCount: 0,
    project: ["proj_1"],
  },
  {
    id: "2",
    name: "Sentiment Analysis",
    description: "Analyze brand sentiment across social media platforms",
    apps: ["Brandwatch", "Twitter API"],
    status: "idle",
    type: "project",
    steps: [
      "collecting mentions",
      "analyzing sentiment",
      "generating summary",
      "notifying marketing team",
    ],
    runCount: 0,
    project: ["proj_1"],
  },
  {
    id: "3",
    name: "Performance Report",
    description: "Generate weekly performance report for brand campaign",
    apps: ["Google Analytics", "Google Slides"],
    status: "idle",
    type: "project",
    steps: [
      "gathering campaign data",
      "analyzing KPIs",
      "creating slides",
      "sharing with stakeholders",
    ],
    runCount: 0,
    project: ["proj_1"],
  },
  // Website redesign (proj_2) - 5 automations
  {
    id: "4",
    name: "Support Analysis",
    description: "Analyze support tickets and identify patterns",
    apps: ["Zendesk", "Slack"],
    status: "idle",
    type: "project",
    steps: [
      "monitoring tickets in zendesk",
      "categorizing issues",
      "identifying patterns",
      "generating insights",
      "posting to slack #support-analysis",
    ],
    runCount: 0,
    project: ["proj_2"],
  },
  {
    id: "5",
    name: "Feedback Collector",
    description: "Collect and summarize UI feedback from users",
    apps: ["Hotjar", "Google Sheets"],
    status: "idle",
    type: "project",
    steps: [
      "collecting feedback",
      "categorizing issues",
      "summarizing findings",
      "notifying design team",
    ],
    runCount: 0,
    project: ["proj_2"],
  },
  {
    id: "6",
    name: "Accessibility Check",
    description: "Run accessibility checks on new website pages",
    apps: ["axe", "Jira"],
    status: "idle",
    type: "project",
    steps: ["scanning pages", "logging issues in jira", "notifying dev team"],
    runCount: 0,
    project: ["proj_2"],
  },
  {
    id: "7",
    name: "Design Reminder",
    description: "Remind designers to hand off assets for development",
    apps: ["Figma", "Slack"],
    status: "idle",
    type: "project",
    steps: [
      "checking asset status",
      "sending reminders",
      "updating status in slack",
    ],
    runCount: 0,
    project: ["proj_2"],
  },
  {
    id: "8",
    name: "SEO Check",
    description: "Automate SEO checks for redesigned pages",
    apps: ["Ahrefs", "Google Sheets"],
    status: "idle",
    type: "project",
    steps: ["scanning pages", "logging SEO issues", "generating report"],
    runCount: 0,
    project: ["proj_2"],
  },
  // Product launch (proj_3) - 2 automations
  {
    id: "9",
    name: "Project Reminder",
    description: "Remind team members to update project status",
    apps: ["Linear", "GMail"],
    status: "idle",
    type: "project",
    steps: [
      "scanning projects in linear",
      "checking deadlines",
      "sending reminders in gmail",
      "updating status in linear",
    ],
    runCount: 0,
    project: ["proj_3"],
  },
  {
    id: "10",
    name: "Launch Checklist",
    description: "Automate product launch checklist and reminders",
    apps: ["Asana", "Slack"],
    status: "idle",
    type: "project",
    steps: ["checking checklist items", "sending reminders", "updating status"],
    runCount: 0,
    project: ["proj_3"],
  },
  // Square POS Experiment (proj_4) - 4 automations
  {
    id: "11",
    name: "Metrics Monitor",
    description: "Monitor metrics and detect anomalies",
    apps: ["Google Sheets", "LaunchDarkly"],
    status: "idle",
    type: "project",
    steps: [
      "collecting data from launchdarkly",
      "analyzing trends",
      "detecting anomalies",
      "generating alerts",
      "categorizing severity in google sheets",
    ],
    runCount: 0,
    project: ["proj_4"],
  },
  {
    id: "12",
    name: "Integration Test",
    description: "Test Square POS integration with voice automation",
    apps: ["Square API", "Jest"],
    status: "idle",
    type: "project",
    steps: [
      "running integration tests",
      "logging results",
      "notifying dev team",
    ],
    runCount: 0,
    project: ["proj_4"],
  },
  {
    id: "13",
    name: "Anomaly Detection",
    description: "Detect anomalies in POS transactions",
    apps: ["Square API", "Google Sheets"],
    status: "idle",
    type: "project",
    steps: [
      "collecting transaction data",
      "analyzing for anomalies",
      "generating alerts",
    ],
    runCount: 0,
    project: ["proj_4"],
  },
  {
    id: "14",
    name: "Device Monitor",
    description: "Monitor health of POS devices and alert issues",
    apps: ["Square API", "PagerDuty"],
    status: "idle",
    type: "project",
    steps: [
      "checking device status",
      "logging issues",
      "notifying support team",
    ],
    runCount: 0,
    project: ["proj_4"],
  },
  // Unassigned or general automations (7 more to reach 21)
  {
    id: "15",
    name: "Cabinet Deploy",
    description: "Deploy Arcade cabinet app",
    apps: ["Buildkite", "AWS"],
    status: "error",
    type: "general",
    steps: [
      "checking dependencies",
      "running tests",
      "building artifacts in buildkite",
      "deploying changes in aws",
    ],
    runCount: 0,
  },
  {
    id: "16",
    name: "Comment Summary",
    description: "Summarize comments from Figma",
    apps: ["Figma"],
    status: "idle",
    type: "general",
    steps: [
      "scanning threads in figma",
      "extracting key points",
      "generating summary",
      "formatting output",
      "suggesting responses",
    ],
    runCount: 0,
  },
  {
    id: "17",
    name: "PR Review",
    description: "Review PRs and merge them",
    apps: ["GitHub"],
    status: "idle",
    type: "general",
    steps: [
      "analyzing changes in github",
      "checking conflicts",
      "running tests in github actions",
      "generating feedback",
    ],
    runCount: 0,
  },
  {
    id: "18",
    name: "Notes Summary",
    description: "Summarize meeting notes and distribute to team",
    apps: ["Google Meet", "GMail"],
    status: "idle",
    type: "one-off",
    steps: [
      "transcribing meeting",
      "extracting action items",
      "emailing summary",
    ],
    runCount: 0,
  },
  {
    id: "19",
    name: "Expense Report",
    description: "Generate monthly expense reports from receipts",
    apps: ["Expensify", "Google Sheets"],
    status: "idle",
    type: "one-off",
    steps: [
      "collecting receipts",
      "categorizing expenses",
      "generating report",
    ],
    runCount: 0,
  },
  {
    id: "20",
    name: "NPS Survey",
    description: "Send and analyze NPS surveys to customers",
    apps: ["Typeform", "Slack"],
    status: "idle",
    type: "one-off",
    steps: [
      "sending surveys",
      "collecting responses",
      "analyzing results",
      "notifying team",
    ],
    runCount: 0,
  },
  {
    id: "21",
    name: "Incident Response",
    description: "Automate incident response workflow",
    apps: ["PagerDuty", "Slack"],
    status: "idle",
    type: "one-off",
    steps: [
      "detecting incident",
      "notifying responders",
      "tracking resolution",
    ],
    runCount: 0,
  },
];

export const detailedStatuses: Record<Automation["status"], string> = {
  idle: "idle",
  active: "running",
  error: "encountered an error",
};
